services:
  firefly_iii_core:
    image: fireflyiii/core:latest
    hostname: firefly_iii_core
    container_name: firefly_iii_core
    restart: always
    env_file: .env
    ports:
      - 80:8080
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    networks:
      - ingress
    depends_on:
      - db

  db:
    image: mariadb:lts
    hostname: db
    container_name: firefly_iii_db
    restart: always
    env_file: .db.env
    volumes:
      - firefly_iii_db:/var/lib/mysql
    networks:
      - ingress

  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine
    restart: always
    container_name: firefly_iii_cron
    env_file: .env
    command: sh -c "
      apk add tzdata && \
      (ln -s /usr/share/zoneinfo/$$TZ /etc/localtime || true) && \
      echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/$$STATIC_CRON_TOKEN;echo\"
      | crontab - && \
      crond -f -L /dev/stdout"
    networks:
      - ingress
    depends_on:
      - app

volumes:
  firefly_iii_upload:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/docker_volumes/personal_finance_manager/firefly_iii/upload
  firefly_iii_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/docker_volumes/personal_finance_manager/firefly_iii/db

networks:
  ingress:
    external: true
