services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - "${NGINX_PROXY_WEB_INTERFACE_PORT}:81"
    networks:
      - edge
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt

networks:
  edge:
    name: "${PROJECT}"

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${NGINX_PROXY_DATA_VOLUME_PATH}"
  letsencrypt:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${NGINX_PROXY_LETSENCRYPT_VOLUME_PATH}"
